include: package:effective_dart/analysis_options.1.3.1.yaml

linter:
    rules:
        constant_identifier_names: false
        omit_local_variable_types: false
        avoid_types_on_closure_parameters: false
        use_setters_to_change_properties: false
